Candidates.CompanyName='softinnovas';

Candidates c=new Candidates();
c.Name='aysel';
c.Gender='Female';
c.printCandidate();

Candidates c1=new Candidates();
c1.Name='Levent';
c1.Gender=' Male';
c1.printCandidate();

Candidates c2=new Candidates();
c2.Name='Kerem';
c2.Gender=' child ';
c2.printCandidate();

Candidates.CompanyName='SOFT INC.';
c.printCandidate();
c1.printCandidate();
c2.printCandidate();

Candidates.CompanyName='hello';
Candidates.printCandidatesInfoSt();

