Car carObj1 = new Car();

// carObj1.switchOn();

// car bm=new car();
// bm.carColor='black';
// System.debug('car color = '+bm.carColor);
// bm.switchOn();
// System.debug('car obj 1 =' +bm);

// car lm=new car();
// lm.carColor='yellow';
// System.debug('lm car color is '+lm.carColor);
// lm.switchOn();

car vw1=new car();
vw1.carColor='white';
vw1.carName='polo';
vw1.drive();
vw1.driveAtMaxSpeed();
system.debug('vw1='+vw1);