SetDemo.citySet();
SetDemo.randomIntegerSet();


List<integer> l1=new List<Integer>{10,15,21,99,55,44,10,99};

system.debug(SetDemo.setFromList(l1) );


Set<String> cities=new Set<String>();

        cities.add('tokyo');
        cities.add('lisbon');
        cities.add('berlin');
        cities.add('nairobi');
        cities.add('tokyo');

        system.debug( SetDemo.capitalizeSet(cities)
       );